  name: Update stats

  on:
    watch:
      types: started

  jobs:
    update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      if: github.event.repository.owner.id == github.event.sender.id
      steps:
        - uses: athul/waka-readme@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            SHOW_TITLE: true
